version: "3.8"
services:
  mysqldb:
    container_name: mysqldb
    image: mysql:latest
    restart: unless-stopped
    volumes:
      - "./db-data:/var/lib/mysql"
    ports:
      - '3307:3306'
    environment:
      MYSQL_DATABASE: student_management_grades
      MYSQL_DATABASE_1: student_management_users
      MYSQL_ROOT_PASSWORD: studentMANAGEMENT123456
    networks:
      student_management_network:
        ipv4_address: 192.168.70.2

  php_myadmin:
    container_name: php_myadmin
    depends_on:
      - mysqldb
    image: phpmyadmin:latest
    restart: no
    ports:
      - '7080:80'
    environment:
      - PMA_HOST=mysqldb
      - MYSQL_ROOT_PASSWORD=studentMANAGEMENT123456
    networks:
      student_management_network:
        ipv4_address: 192.168.70.5

  student_management_grades-service:
    container_name: student_management_grades-service
    restart: always
    ports:
      - '8081:8081'
    depends_on:
      - mysqldb
    build:
      context: grade-service/
      dockerfile: Dockerfile
    environment:
      - spring.jpa.hibernate.ddl-auto=update
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/student_management_grades
      - spring.datasource.username=root
      - spring.datasource.password=studentMANAGEMENT123456
      - spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
      - server.port=8081
      - spring.application.name=grade-service
      - spring.application.version=1.0.0
      - spring.application.authors=Digital_Zone
      - spring.cloud.discovery.enabled=true
      - eureka.client.service-url.defaultZone=http://192.168.70.20:8761/eureka
      - logging.level.org.springframework.validation=DEBUG
    networks:
      student_management_network:
        ipv4_address: 192.168.70.23

  student_management_discovery-service:
    container_name: student_management_discovery-service
    ports:
      - '8761:8761'
    build:
      context: discovery-service/
      dockerfile: Dockerfile
    environment:
      - server.port=8761
      - spring.application.name=eureka-server
      - eureka.client.registerWithEureka=false
      - eureka.client.fetchRegistry=false
      - eureka.instance.hostname=localhost
      - eureka.client.serviceUrl.defaultZone = http://localhost:8761/eureka
    networks:
      student_management_network:
        ipv4_address: 192.168.70.20

  student_management_gateway-service:
    container_name: student_management_gateway-service
    ports:
      - '8888:8888'
    build:
      context: gateway-service/
      dockerfile: Dockerfile
    environment:
      - spring.application.authors=Digital_Zone
      - spring.cloud.discovery.enabled=true
      - eureka.client.service-url.defaultZone=http://192.168.70.20:8761/eureka
      - logging.level.org.springframework.validation=DEBUG
    networks:
      student_management_network:
        ipv4_address: 192.168.70.10

  student_management_user-service:
    container_name: student_management_user-service
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      - mysqldb
    build:
      context: user-service/
      dockerfile: Dockerfile
    environment:
      - spring.jpa.hibernate.ddl-auto=update
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/student_management_users
      - spring.datasource.username=root
      - spring.datasource.password=studentMANAGEMENT123456
      - spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
      - server.port=8080
      - spring.application.name=user-service
      - spring.application.version=1.0.0
      - spring.application.authors=Digital_Zone
      - spring.cloud.discovery.enabled=true
      - eureka.client.service-url.defaultZone=http://192.168.70.20:8761/eureka
      - logging.level.org.springframework.validation=DEBUG
      - app.jwt.secret-key=586E5A7234753778214125442A472D4B6150645367566B59703373357638792F
      - app.jwt.expiration=86400000
      - spring.mail.host=smtp.gmail.com
      - spring.mail.port=587
      - spring.mail.username=heptagrammers@gmail.com
      - spring.mail.password=rwlbwyilifqzdtux
      - spring.mail.properties.mail.smtp.auth=true
      - spring.mail.properties.mail.smtp.starttls.enable=true
    networks:
      student_management_network:
        ipv4_address: 192.168.70.22
networks:
  student_management_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.70.0/24
          gateway: 192.168.70.1
