server:
  port: 8888
spring:
  application:
    name: gateway-service
  cloud:
    discovery:
      enabled: true
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/users/**

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/auth/**

        - id: garde-service
          uri: lb://GRADE-SERVICE
          predicates:
            - Path=/api/v1/grades/**
          filters:
            - AuthenticationFilter

        - id: subject-service
          uri: lb://SUBJECT-SERVICE
          predicates:
            - Path=/api/v1/subjects/**
          filters:
            - AuthenticationFilter

        - id: attendance-service
          uri: lb://ATTENDANCE-SERVICE
          predicates:
            - Path=/api/v1/attendance/**
          filters:
            - AuthenticationFilter

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE